### PR TITLE
better formatting

### PR DESCRIPTION
**Pull request by gforcada**

### CODE REVIEW

**Comment by frisi** [comment]
i think you'll need to update the MANIFEST.in to include the *.rst files too, otherwhise the next release could be broken.
i'd squash these commits into a single one to have a cleaner history

**Comment by gforcada** [comment]
Sure, I was doing it lazily from github UI, that's why there's one commit per file :)

**Comment by gforcada** [comment]
@frisi MANIFEST.in fixed and everything squashed into a single commit. Let me know if you think there's something else missing.

**Comment by frisi** [comment]
@gforcada: I'd go for `include *.cfg *.rst *.txt` in MANIFEST.in although the txt files should not necessary for installing the released egg. after that ready to merge. have a nice weekend!

**Comment by gforcada** [comment]
Done

**Comment by gforcada** [comment]
@frisi ping :)

**Comment by frisi** [comment]
sorry @gforcada - when i read "done" in the email i thought you have merged it yourself ;-)

**Pull request merged**
